"""auto-test

Revision ID: d080d559178e
Revises: 36a145ca2565
Create Date: 2023-05-23 13:27:14.776931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd080d559178e'
down_revision = '36a145ca2565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
